$('#menuButton').on('click',function(event){
    event.preventDefault();
    event.stopImmediatePropagation();
    $('body').toggleClass('menuOpen');
}).on('touchstart',function(event){
    event.preventDefault();
    event.stopImmediatePropagation();
    $('body').toggleClass('menuOpen');
});
